// Builds `oracle/index.js` — a self-contained ESM bundle that re-exports the
// *pure* math functions from the vendored upstream sources under `xyflow/`.
// This bundle is the XYFlow "oracle" the live parity tests (Layer 1) compare
// PSFlow against. It is published to the workspace as the bare specifier
// `@psflow/oracle` via a `file:./oracle` devDependency, mirroring how PSFlow
// already imports `d3-zoom` and friends from FFI.
//
// Why this is safe to bundle (no d3 / no React in the output):
//   * `@xyflow/system` declares `"sideEffects": false`, so esbuild
//     tree-shakes the d3-using leaves (xydrag/xypanzoom/…) we never touch.
//   * `getSimpleBezierPath` lives in the React package; esbuild tree-shakes
//     the surrounding `memo()` component and `--external` keeps the React
//     runtime out of the bundle.
//
// The entry list below is the single source of truth for "which upstream
// pure functions are under parity test". Add a line here + a property in
// `test/Test/Parity/*` to extend coverage. Rebuild with `npm run build:oracle`
// (and re-run it whenever `xyflow/` is bumped).

import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { readFileSync } from "node:fs";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const xyflow = (p) => resolve(repoRoot, "xyflow", p);
const readJson = (p) => JSON.parse(readFileSync(p, "utf8"));

const reactVersion = readJson(xyflow("packages/react/package.json")).version;
const systemVersion = readJson(xyflow("packages/system/package.json")).version;

// The entry module. Paths are relative to `resolveDir` (the repo root) so the
// vendored sources resolve directly; esbuild strips the TypeScript types.
const entry = `
export { getEdgeCenter } from "./xyflow/packages/system/src/utils/edges/general";
export { getStraightPath } from "./xyflow/packages/system/src/utils/edges/straight-edge";
export { getBezierPath, getBezierEdgeCenter } from "./xyflow/packages/system/src/utils/edges/bezier-edge";
export { getSmoothStepPath } from "./xyflow/packages/system/src/utils/edges/smoothstep-edge";
export { getSimpleBezierPath } from "./xyflow/packages/react/src/components/Edges/SimpleBezierEdge";
export {
  clamp,
  clampPosition,
  getBoundsOfBoxes,
  rectToBox,
  boxToRect,
  getBoundsOfRects,
  getOverlappingArea,
  snapPosition,
  pointToRendererPoint,
  rendererPointToPoint
} from "./xyflow/packages/system/src/utils/general";
`;

await build({
  stdin: { contents: entry, resolveDir: repoRoot, loader: "ts", sourcefile: "oracle-entry.ts" },
  bundle: true,
  format: "esm",
  platform: "neutral",
  // Keep the React runtime out — getSimpleBezierPath's host component is
  // tree-shaken, but the file references these specifiers.
  external: ["react", "react-dom", "react/jsx-runtime"],
  // The React package imports the system package by its published name.
  alias: { "@xyflow/system": xyflow("packages/system/src/index.ts") },
  jsx: "automatic",
  banner: {
    js:
      `// @psflow/oracle — GENERATED by oracle/esbuild.mjs. DO NOT EDIT.\n` +
      `// Vendored XYFlow pure functions for live parity testing (Layer 1).\n` +
      `// Source: @xyflow/react ${reactVersion} / @xyflow/system ${systemVersion}.\n` +
      `// Rebuild: npm run build:oracle (re-run on every xyflow/ bump).`,
  },
  outfile: resolve(here, "index.js"),
  logLevel: "info",
});
