// Builds `oracle/index.js` — a self-contained ESM bundle that re-exports the
// *pure* functions from the vendored upstream sources under `xyflow/`.
// This bundle is the XYFlow "oracle" the live parity tests (Layer 1) compare
// PSFlow against. It is published to the workspace as the bare specifier
// `@psflow/oracle` via a `file:./oracle` devDependency, mirroring how PSFlow
// already imports `d3-zoom` and friends from FFI.
//
// Why this is safe to bundle (no d3 / no React in the output):
//   * `@xyflow/system` declares `"sideEffects": false`, so esbuild
//     tree-shakes the d3-using leaves (xydrag/xypanzoom/…) we never touch.
//   * `getSimpleBezierPath` lives in the React package; esbuild tree-shakes
//     the surrounding `memo()` component and `--external` keeps the React
//     runtime out of the bundle. The same holds for the React package's
//     `utils/` modules — `changes`, `edges` and `general` are plain data
//     functions whose file-level React imports the entry list never reaches.
//
// The entry list below is the single source of truth for "which upstream
// pure functions are under parity test". Add a line here + a property in
// `test/Test/Parity/*` to extend coverage. Rebuild with `npm run build:oracle`
// (and re-run it whenever `xyflow/` is bumped).

import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { readFileSync } from "node:fs";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const xyflow = (p) => resolve(repoRoot, "xyflow", p);
const readJson = (p) => JSON.parse(readFileSync(p, "utf8"));

const reactVersion = readJson(xyflow("packages/react/package.json")).version;
const systemVersion = readJson(xyflow("packages/system/package.json")).version;

// The entry module. Paths are relative to `resolveDir` (the repo root) so the
// vendored sources resolve directly; esbuild strips the TypeScript types.
const entry = `
export { getEdgeCenter } from "./xyflow/packages/system/src/utils/edges/general";
export { getStraightPath } from "./xyflow/packages/system/src/utils/edges/straight-edge";
export { getBezierPath, getBezierEdgeCenter } from "./xyflow/packages/system/src/utils/edges/bezier-edge";
export { getSmoothStepPath } from "./xyflow/packages/system/src/utils/edges/smoothstep-edge";
export { getSimpleBezierPath } from "./xyflow/packages/react/src/components/Edges/SimpleBezierEdge";
export {
  clamp,
  clampPosition,
  getBoundsOfBoxes,
  rectToBox,
  boxToRect,
  getBoundsOfRects,
  getOverlappingArea,
  snapPosition,
  pointToRendererPoint,
  rendererPointToPoint,
  getViewportForBounds
} from "./xyflow/packages/system/src/utils/general";
export { getNodeToolbarTransform } from "./xyflow/packages/system/src/utils/node-toolbar";
export { getEdgeToolbarTransform } from "./xyflow/packages/system/src/utils/edge-toolbar";
export { getMarkerId } from "./xyflow/packages/system/src/utils/marker";
export { getConnectionStatus } from "./xyflow/packages/system/src/utils/connections";
export { getOutgoers, getIncomers, getConnectedEdges, getNodesBounds } from "./xyflow/packages/system/src/utils/graph";
export { applyNodeChanges, applyEdgeChanges } from "./xyflow/packages/react/src/utils/changes";
// The React-layer \`addEdge\`/\`reconnectEdge\` (not the system ones they
// delegate to) — those are the names \`@xyflow/react\` exports, and the layer
// they add is an \`onError\` default the parity property overrides.
export { addEdge, reconnectEdge } from "./xyflow/packages/react/src/utils/edges";
export { isNode, isEdge } from "./xyflow/packages/react/src/utils/general";
`;

await build({
  stdin: { contents: entry, resolveDir: repoRoot, loader: "ts", sourcefile: "oracle-entry.ts" },
  bundle: true,
  format: "esm",
  platform: "neutral",
  // Keep the React runtime out — getSimpleBezierPath's host component is
  // tree-shaken, but the file references these specifiers.
  external: ["react", "react-dom", "react/jsx-runtime"],
  // The React package imports the system package by its published name.
  alias: { "@xyflow/system": xyflow("packages/system/src/index.ts") },
  jsx: "automatic",
  // `getNodesBounds` branches on `process.env.NODE_ENV` to decide whether to
  // warn about a missing nodeLookup. A `platform: "neutral"` bundle has no
  // `process`, so the reference is substituted rather than left to resolve
  // against whatever host loads the bundle — and pinning it to "production"
  // keeps the dev warning out of the parity run's output.
  define: { "process.env.NODE_ENV": '"production"' },
  banner: {
    js:
      `// @psflow/oracle — GENERATED by oracle/esbuild.mjs. DO NOT EDIT.\n` +
      `// Vendored XYFlow pure functions for live parity testing (Layer 1).\n` +
      `// Source: @xyflow/react ${reactVersion} / @xyflow/system ${systemVersion}.\n` +
      `// Rebuild: npm run build:oracle (re-run on every xyflow/ bump).`,
  },
  outfile: resolve(here, "index.js"),
  logLevel: "info",
});
