// Census generator — ticket #15 on wayfinder map #14.
//
// Joins the hand-curated `classification.json` against the machine-extracted
// Layer 0 surface (`../layer0-api/upstream.json`, `psflow.json`) and the Layer 1
// oracle bundle (`../../oracle/index.js`), and writes `report.md`.
//
// The point of generating rather than hand-writing the table: on a baseline
// bump, `npm run parity:api` refreshes upstream.json, and this script then
// *fails* on any export that appeared or vanished without being classified.
// A census that silently goes stale is worse than none.
//
//   node parity/census/build.mjs
//
// Exit 1 = the classification no longer matches the surface. Fix
// classification.json, don't loosen this script.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const read = (p) => JSON.parse(readFileSync(join(here, p), "utf8"));

const upstream = read("../layer0-api/upstream.json");
const psflow = read("../layer0-api/psflow.json");
const classification = read("./classification.json");

const oracleSrc = readFileSync(join(here, "../../oracle/index.js"), "utf8");
const oracleExports = new Set(
  (oracleSrc.match(/export \{([\s\S]*?)\};/)?.[1] ?? "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean)
);

const upstreamValues = new Set(upstream.valueExports);
const upstreamNames = [...upstream.valueExports, ...upstream.typeExports];
const psValues = new Set(psflow.valueExports);
const psTypes = new Set(psflow.typeExports);

// ── Consistency gates ──────────────────────────────────────────────────────
const classified = Object.keys(classification).filter((k) => !k.startsWith("_"));
const errors = [];

const unclassified = upstreamNames.filter((n) => !(n in classification));
if (unclassified.length) {
  errors.push(`Unclassified upstream exports (${unclassified.length}): ${unclassified.join(", ")}`);
}
const stale = classified.filter((n) => !upstreamNames.includes(n));
if (stale.length) {
  errors.push(`Classified names no longer in the upstream surface (${stale.length}): ${stale.join(", ")}`);
}

// An L1 claim on a pure function must be backed by the oracle bundle actually
// exporting it — the one gate claim we can verify mechanically.
for (const name of upstreamNames) {
  const entry = classification[name];
  if (!entry) continue;
  const [kind, , gates] = entry;
  if (kind !== "pure-fn") continue;
  const claimsL1 = gates.includes("L1");
  const inOracle = oracleExports.has(name);
  if (claimsL1 && !inOracle) {
    errors.push(`${name} claims L1 but oracle/index.js does not export it.`);
  }
  if (!claimsL1 && inOracle) {
    errors.push(`${name} is in the oracle bundle but does not claim L1.`);
  }
}

if (errors.length) {
  console.error("Census is out of date:\n" + errors.map((e) => "  - " + e).join("\n"));
  process.exit(1);
}

// ── Report ─────────────────────────────────────────────────────────────────
const KIND_ORDER = [
  "component", "hook", "pure-fn", "enum-value",
  "props", "callback", "change", "data", "options",
  "instance-api", "store", "internal-type",
];

const rows = upstreamNames
  .map((name) => {
    const [kind, mechanism, gates, note] = classification[name];
    return {
      name,
      kind,
      mechanism,
      gates,
      note,
      upstreamValue: upstreamValues.has(name),
      psValue: psValues.has(name),
      psType: psTypes.has(name),
    };
  })
  .sort((a, b) => {
    const k = KIND_ORDER.indexOf(a.kind) - KIND_ORDER.indexOf(b.kind);
    return k !== 0 ? k : a.name.localeCompare(b.name);
  });

const beyondL0 = (r) => r.gates.filter((g) => g !== "L2-indirect").length > 0;
const provenByNothing = (r) => r.gates.length === 0;

const tally = (pred) => rows.filter(pred).length;
const byKind = KIND_ORDER.map((kind) => {
  const ks = rows.filter((r) => r.kind === kind);
  return {
    kind,
    total: ks.length,
    gated: ks.filter(beyondL0).length,
    indirect: ks.filter((r) => !beyondL0(r) && r.gates.length > 0).length,
    nothing: ks.filter(provenByNothing).length,
  };
}).filter((r) => r.total > 0);

const gateCell = (r) => (r.gates.length ? r.gates.join(" + ") : "—");

const out = [];
out.push("# Export census — which gate can prove which public export?");
out.push("");
out.push("_Generated by `node parity/census/build.mjs` — edit `classification.json`, not this file._");
out.push("");
out.push(`Surface: \`@xyflow/react\` **${upstream.reactVersion}** / \`@xyflow/system\` **${upstream.systemVersion}** — ` +
  `${upstreamNames.length} top-level exports (${upstream.valueExports.length} value + ${upstream.typeExports.length} type), ` +
  "as enumerated by `parity/layer0-api/upstream.json`.");
out.push("");
out.push("Every row is covered by Layer 0 (`npm run parity:api`) for **name presence**. The");
out.push("`Gates today` column lists only what reaches further than that. `L2-indirect` means");
out.push("the export is mounted or traversed by a smoke fixture but no assertion targets it —");
out.push("it would not fail if the behaviour diverged.");
out.push("");

out.push("## Summary by kind");
out.push("");
out.push("| Kind | Total | Gated beyond name | Indirect only | Nothing but the name |");
out.push("|---|---:|---:|---:|---:|");
for (const r of byKind) {
  out.push(`| \`${r.kind}\` | ${r.total} | ${r.gated} | ${r.indirect} | ${r.nothing} |`);
}
out.push(`| **total** | **${rows.length}** | **${tally(beyondL0)}** | ` +
  `**${tally((r) => !beyondL0(r) && r.gates.length > 0)}** | **${tally(provenByNothing)}** |`);
out.push("");

out.push("## Summary by mechanism");
out.push("");
out.push("What *could* prove each export, if the dual-run net were built to reach it.");
out.push("");
out.push("| Mechanism | Exports | Of which gated beyond name |");
out.push("|---|---:|---:|");
const mechs = [...new Set(rows.map((r) => r.mechanism))].sort();
for (const m of mechs) {
  const ms = rows.filter((r) => r.mechanism === m);
  out.push(`| \`${m}\` | ${ms.length} | ${ms.filter(beyondL0).length} |`);
}
out.push("");

const jsUnreachable = rows.filter((r) => r.upstreamValue && !r.psValue);
out.push("## Upstream values with no PSFlow runtime counterpart");
out.push("");
out.push("Layer 0 compares names as a value-union-type set, so an upstream **runtime object**");
out.push("that PSFlow surfaces only as a PureScript **type** passes the gate. For a JS/TS");
out.push("consumer — the audience this repo exists for — the import is `undefined`.");
out.push("");
out.push("| Export | PSFlow surfaces | Reachable by |");
out.push("|---|---|---|");
for (const r of jsUnreachable) {
  out.push(`| \`${r.name}\` | ${r.psType ? "PureScript type only" : "nothing"} | ${gateCell(r)} |`);
}
out.push("");

out.push("## Full census");
out.push("");
out.push("| Export | Kind | Mechanism that could prove it | Gates today | Notes |");
out.push("|---|---|---|---|---|");
for (const r of rows) {
  out.push(`| \`${r.name}\` | ${r.kind} | \`${r.mechanism}\` | ${gateCell(r)} | ${r.note} |`);
}
out.push("");

writeFileSync(join(here, "report.md"), out.join("\n"));
console.log(
  `Census OK — ${rows.length} exports classified; ` +
  `${tally(beyondL0)} gated beyond name presence, ${tally(provenByNothing)} proven by nothing.`
);
