// Layer 0 — diff + report generator. Compares the upstream and PSFlow API
// surfaces extracted by the sibling scripts, subtracts the documented
// divergence allowlist, and writes `report.md` (a committed parity snapshot).
//
// Gate: a non-empty "missing in PSFlow" export bucket *after* allowlisting is
// a parity gap → non-zero exit, so `npm run parity:api` can fail CI. Prop and
// extra buckets are reported but informational (the prop surface carries a lot
// of legitimate version drift and React-ism differences).

import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const here = dirname(fileURLToPath(import.meta.url));
const load = (name) => JSON.parse(readFileSync(join(here, name), "utf8"));

const upstream = load("upstream.json");
const psflow = load("psflow.json");
const allowPath = join(here, "allowlist.json");
const allow = existsSync(allowPath)
  ? load("allowlist.json")
  : { exports: { missing: {}, extra: {} }, props: {} };

const allowMissing = allow.exports?.missing ?? {};
const allowExtra = allow.exports?.extra ?? {};

const setOf = (xs) => new Set(xs);
const diff = (a, b) => [...a].filter((x) => !b.has(x)).sort();

// Unified name set per side. PSFlow models several TS enums (MarkerType,
// Position, …) as PureScript *types* where TS exports them as runtime
// *values*; comparing the union of value+type names sidesteps that
// value/type-classification mismatch and keeps the diff focused on genuinely
// absent/extra symbols.
const upstreamAll = setOf([...upstream.valueExports, ...upstream.typeExports]);
const psflowAll = setOf([...psflow.valueExports, ...psflow.typeExports]);

const missingRaw = diff(upstreamAll, psflowAll);
const extraRaw = diff(psflowAll, upstreamAll);

const partition = (names, allowMap) => {
  const known = [];
  const unexpected = [];
  for (const n of names) {
    if (Object.prototype.hasOwnProperty.call(allowMap, n)) known.push(n);
    else unexpected.push(n);
  }
  return { known, unexpected };
};

const missing = partition(missingRaw, allowMissing);
const extra = partition(extraRaw, allowExtra);

// ─── Prop diffs (informational) ───────────────────────────────────────────
const propDiff = (name) => {
  const up = setOf(upstream.props[name] ?? []);
  const ps = setOf(psflow.props[name] ?? []);
  return { missing: diff(up, ps), extra: diff(ps, up) };
};
const propResults = {
  ReactFlowProps: propDiff("ReactFlowProps"),
  NodeProps: propDiff("NodeProps"),
  EdgeProps: propDiff("EdgeProps"),
};

// ─── Report ───────────────────────────────────────────────────────────────
const now = new Date().toISOString().slice(0, 10);
const list = (xs) => (xs.length ? xs.map((x) => `\`${x}\``).join(", ") : "_none_");
const knownTable = (names, allowMap) =>
  names.length
    ? names.map((n) => `| \`${n}\` | ${allowMap[n]} |`).join("\n")
    : "| _none_ | |";

const propSection = (name, r) => {
  const drift = (allow.props?.[name]?.drift) ?? {};
  const annotate = (x) => (drift[x] ? `\`${x}\` _(${drift[x]})_` : `\`${x}\``);
  return [
    `### ${name}`,
    "",
    `- upstream members: ${upstream.props[name].length}, PSFlow members: ${psflow.props[name].length}`,
    `- **missing in PSFlow** (${r.missing.length}): ${r.missing.length ? r.missing.map(annotate).join(", ") : "_none_"}`,
    `- **extra in PSFlow** (${r.extra.length}): ${list(r.extra)}`,
    "",
  ].join("\n");
};

const report = `# Layer 0 — API-surface parity report

_Generated by \`npm run parity:api\` — do not edit by hand. Last run: ${now}._

Upstream: \`@xyflow/react\` **${upstream.reactVersion}** / \`@xyflow/system\` **${upstream.systemVersion}**.
PSFlow was originally ported against \`@xyflow/react@^12.3.5\`. Every changelog
entry between that floor and the baseline above has since been bucketed by the
12.3.5→12.11.0 drift audit (ticket 071), so a divergence below is a genuine
port gap, not unclassified version drift — see
[\`parity/changelog-audit/report.md\`](../changelog-audit/report.md).

Method: top-level exports are extracted from upstream via the TypeScript
compiler API (resolves \`export *\`, renames, type-only exports) and from
PSFlow via \`index.js\` (values) + \`src/React.purs\` (types). Names are compared
as a value∪type union to neutralise the enum-as-value (TS) vs
sum-type-as-type (PS) modelling difference.

## Top-level exports

- upstream: ${upstreamAll.size} names (${upstream.valueExports.length} value + ${upstream.typeExports.length} type)
- PSFlow: ${psflowAll.size} names (${psflow.valueExports.length} value + ${psflow.typeExports.length} type)

### ❌ Missing in PSFlow (parity gaps — gates CI)

${missing.unexpected.length ? missing.unexpected.map((x) => `- \`${x}\``).join("\n") : "_none — full parity (modulo the allowlist below)._"}

### ➕ Extra in PSFlow (extensions / PS-idiom — informational)

${extra.unexpected.length ? extra.unexpected.map((x) => `- \`${x}\``).join("\n") : "_none._"}

### 📋 Known divergences (allowlisted)

**Intentionally absent from PSFlow:**

| Symbol | Rationale |
|--------|-----------|
${knownTable(missing.known, allowMissing)}

**PSFlow-only, intentional:**

| Symbol | Rationale |
|--------|-----------|
${knownTable(extra.known, allowExtra)}

## Prop-member parity (informational)

Members are restricted to those declared in the xyflow sources (inherited React
DOM attributes are excluded on both sides). The \`xPos\`/\`yPos\` →
\`positionAbsoluteX\`/\`positionAbsoluteY\` rename that this section surfaced was
closed by ticket 069; the remaining annotations below record which upstream
name a PSFlow member corresponds to.

${propSection("ReactFlowProps", propResults.ReactFlowProps)}
${propSection("NodeProps", propResults.NodeProps)}
${propSection("EdgeProps", propResults.EdgeProps)}
`;

writeFileSync(join(here, "report.md"), report);

// ─── Console summary + gate ───────────────────────────────────────────────
console.log(`[diff] missing(gap)=${missing.unexpected.length} extra=${extra.unexpected.length} ` +
  `allowlisted(missing)=${missing.known.length} allowlisted(extra)=${extra.known.length}`);
console.log(`[diff] props missing: RF=${propResults.ReactFlowProps.missing.length} ` +
  `Node=${propResults.NodeProps.missing.length} Edge=${propResults.EdgeProps.missing.length}`);
console.log(`[diff] report → ${join(here, "report.md")}`);

if (missing.unexpected.length > 0) {
  console.error(`\n[diff] FAIL: ${missing.unexpected.length} upstream export(s) missing from PSFlow and not allowlisted:`);
  for (const n of missing.unexpected) console.error(`  - ${n}`);
  console.error("Triage into a ticket and add to allowlist.json, or surface the gap.");
  process.exit(1);
}
console.log("[diff] OK: no un-allowlisted missing exports.");
